"""
infer.py — MediQ T5-Small Report Summarization Inference & Test Generation

Generates abstractive summaries from fine-tuned T5-small checkpoints:
  - Accepts input text via CLI argument (--text) or file path (--input_file).
  - Enforces T5 text-to-text task prefix: 'summarize: '.
  - Supports CPU fallback and automatic CUDA GPU inference.
  - Mandates clear non-clinical safety disclaimers.
  - Safe against missing models: exits cleanly without fabricating output.

Usage Examples:
  # Preflight validation check (no weights required):
  python infer.py --validate_only

  # Run inference using trained checkpoint:
  python infer.py \
      --checkpoint exports/t5_small_summarizer \
      --text "A 5-year study evaluated the long-term metabolic outcomes of lifestyle interventions..."
"""

import argparse
import logging
from pathlib import Path
import sys
from typing import Optional

import torch

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("infer_t5_report")

DISCLAIMER_NOTICE = (
    "\n" + "=" * 70 + "\n"
    "CLINICAL SAFETY DISCLAIMER:\n"
    "This summary was generated by an experimental AI model fine-tuned on scientific\n"
    "literature (PubMed). It is intended solely as an information retrieval aid.\n"
    "It is NOT a medical diagnosis, does NOT constitute clinical treatment advice,\n"
    "and must NOT replace professional evaluation by a qualified healthcare provider.\n"
    + "=" * 70
)


def generate_summary(
    checkpoint_path: Path,
    text: str,
    prefix: str = "summarize: ",
    max_length: int = 128,
    min_length: int = 30,
    num_beams: int = 4,
    device: str = "auto",
) -> str:
    """Loads fine-tuned model and produces an abstractive summary."""
    from transformers import AutoTokenizer, T5ForConditionalGeneration

    if device == "auto":
        target_device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        target_device = device

    logger.info(f"Loading summarizer from: {checkpoint_path}...")
    tokenizer = AutoTokenizer.from_pretrained(checkpoint_path)
    model = T5ForConditionalGeneration.from_pretrained(checkpoint_path).to(target_device)
    model.eval()

    clean_text = text.strip()
    if not clean_text.startswith(prefix):
        input_text = prefix + clean_text
    else:
        input_text = clean_text

    inputs = tokenizer(
        input_text,
        max_length=512,
        truncation=True,
        padding=False,
        return_tensors="pt",
    ).to(target_device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_length=max_length,
            min_length=min_length,
            num_beams=num_beams,
            no_repeat_ngram_size=3,
            early_stopping=True,
        )

    summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return summary


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="MediQ T5-Small Report Summarization Test Generation CLI."
    )
    base_dir = Path(__file__).resolve().parent

    p.add_argument(
        "--checkpoint",
        type=str,
        default=None,
        help="Path to trained T5-small model checkpoint directory (defaults to exports/t5_small_summarizer)",
    )
    p.add_argument(
        "--text",
        type=str,
        default=None,
        help="Direct input article or report text string to summarize",
    )
    p.add_argument(
        "--input_file",
        type=Path,
        default=None,
        help="Path to text file containing report or article content",
    )
    p.add_argument(
        "--max_length",
        type=int,
        default=128,
        help="Maximum generated summary length in tokens (default: 128)",
    )
    p.add_argument(
        "--min_length",
        type=int,
        default=30,
        help="Minimum generated summary length in tokens (default: 30)",
    )
    p.add_argument(
        "--num_beams",
        type=int,
        default=4,
        help="Beam search width for generation (default: 4)",
    )
    p.add_argument(
        "--device",
        type=str,
        default="auto",
        choices=["auto", "cpu", "cuda"],
        help="Execution device (default: auto)",
    )
    p.add_argument(
        "--validate_only",
        action="store_true",
        help="Validate arguments and checkpoint existence without generating text",
    )
    return p


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parent

    # Determine checkpoint
    if args.checkpoint:
        ckpt_path = Path(args.checkpoint).resolve()
    else:
        primary_ckpt = base_dir / "exports" / "t5_small_summarizer"
        secondary_ckpt = base_dir / "checkpoints" / "best"
        ckpt_path = primary_ckpt if primary_ckpt.exists() else secondary_ckpt

    # Preflight check
    if args.validate_only:
        logger.info("=== Preflight Inference Check: MediQ T5 Summarizer ===")
        logger.info(f"  Target checkpoint: {ckpt_path}")
        model_status = "EXISTS" if ckpt_path.exists() else "AWAITING_TRAINING (cleanly detected)"
        logger.info(f"  Model status     : {model_status}")
        logger.info("INFERENCE PIPELINE VALIDATION PASSED. Exiting without execution per --validate_only.")
        return

    # Check model presence
    if not ckpt_path.exists():
        logger.error(
            f"Cannot run inference: trained checkpoint not found at: {ckpt_path}\n"
            "Please fine-tune the model in Google Colab first:\n"
            "    python train.py --google_drive"
        )
        sys.exit(1)

    # Resolve input text
    input_text = ""
    if args.text:
        input_text = args.text
    elif args.input_file:
        if not args.input_file.exists():
            logger.error(f"Input file not found: {args.input_file}")
            sys.exit(1)
        input_text = args.input_file.read_text(encoding="utf-8")
    else:
        logger.error("Please provide input text via --text or --input_file.")
        sys.exit(1)

    summary = generate_summary(
        checkpoint_path=ckpt_path,
        text=input_text,
        max_length=args.max_length,
        min_length=args.min_length,
        num_beams=args.num_beams,
        device=args.device,
    )

    print("\n" + "-" * 70)
    print("GENERATED SUMMARY:")
    print("-" * 70)
    print(summary)
    print(DISCLAIMER_NOTICE)


if __name__ == "__main__":
    main()
